# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
jobs:
  - job: job1
    pool:
     vmImage: windows-latest
     name: Default
    steps:
      - task: Maven@4
        continueOnError: true
        inputs:
         mavenPomFile: 'pom.xml'
         goals: 'package'
         publishJUnitResults: true
         testResultsFiles: 'TestNG.xml'
         javaHomeOption: 'Path'
         jdkDirectory: 'C:\Program Files\Java\jdk-11.0.14'
         mavenVersionOption: 'Path'
         mavenDirectory: 'D:\anirban\apache-maven-3.9.0'
         mavenSetM2Home: true
         mavenAuthenticateFeed: false
         effectivePomSkip: false
         sonarQubeRunAnalysis: false
      - task: DeleteFiles@1
        continueOnError: true
        inputs:
          SourceFolder: 'C:/target/*.*'
          Contents: 'delete files under target folder'
      - task: CopyFiles@2
        continueOnError: true
        inputs:
          SourceFolder: 'target'
          Contents: '**'
          TargetFolder: 'C:/target'
          OverWrite: true
          preserveTimestamp: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '/target/cucumber-report/CucumberExtentLogReport.html'
          publishLocation: 'pipeline'
          artifact: TestResult
      - task: PublishHtmlReport@1
        inputs:
          reportDir: '/target/cucumber-report/CucumberExtentLogReport.html'
      - task: NodeTool@0
        displayName: 'Install Node 12.x'
        inputs:
         versionSpec: 12.x
      - task: PublishCucumberReport@1
        inputs:
          jsonDir: '/target/'
          outputPath: '/target/'
          theme: 'bootstrap'
          reportSuiteAsScenarios: true
          name: 'HTML_REPORT_CUCUMBER'
          title: 'Execution report'