# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
jobs:
  - job: job1
    pool:
     vmImage: windows-latest
     name: Default
    steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'Azure subscription 1(cca1ed89-ca0a-432f-b3dd-1dee7e2db00c)'
          azureContainerRegistry: '{"loginServer":"registryarc.azurecr.io", "id" : "/subscriptions/cca1ed89-ca0a-432f-b3dd-1dee7e2db00c/resourceGroups/sg-rg-na/providers/Microsoft.ContainerRegistry/registries/registryarc"}'
          dockerComposeFile: 'docker-compose.yml'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: 'docker-compose -f docker-compose.yml up'
      - task: Maven@4
        continueOnError: true
        inputs:
         mavenPomFile: 'pom.xml'
         goals: 'package'
         publishJUnitResults: true
         testResultsFiles: 'TestNG.xml'
         javaHomeOption: 'Path'
         jdkDirectory: 'C:\Program Files\Java\jdk-11.0.14'
         mavenVersionOption: 'Path'
         mavenDirectory: 'D:\anirban\apache-maven-3.9.0'
         mavenSetM2Home: true
         mavenAuthenticateFeed: false
         effectivePomSkip: false
         sonarQubeRunAnalysis: false
      - task: DeleteFiles@1
        continueOnError: true
        inputs:
          SourceFolder: 'D:/target/*.*'
          Contents: 'delete files under target folder'
      - task: CopyFiles@2
        continueOnError: true
        inputs:
          SourceFolder: 'target'
          Contents: '**'
          TargetFolder: 'D:/target'
          OverWrite: true
          preserveTimestamp: true
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '/target/cucumber-report/CucumberExtentLogReport.html'
          publishLocation: 'pipeline'
          artifact: TestResult
      - task: PublishHtmlReport@1
        inputs:
          reportDir: '/target/cucumber-report/CucumberExtentLogReport.html'
      - task: NodeTool@0
        displayName: 'Install Node 12.x'
        inputs:
         versionSpec: 12.x
      - task: PublishCucumberReport@1
        inputs:
          jsonDir: '/target/'
          outputPath: '/target/'
          theme: 'bootstrap'
          reportSuiteAsScenarios: true
          name: 'HTML_REPORT_CUCUMBER'
          title: 'Execution report'
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'Azure subscription 1(cca1ed89-ca0a-432f-b3dd-1dee7e2db00c)'
          azureContainerRegistry: '{"loginServer":"registryarc.azurecr.io", "id" : "/subscriptions/cca1ed89-ca0a-432f-b3dd-1dee7e2db00c/resourceGroups/sg-rg-na/providers/Microsoft.ContainerRegistry/registries/registryarc"}'
          dockerComposeFile: 'docker-compose.yml'
          action: 'Run a Docker Compose command'
          dockerComposeCommand: 'docker-compose down -f docker-compose.yml'